# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master
      - develop
      - features/*
  paths:
    include:
      - pom.xml

resources:
- repo: self

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DownloadSecureFile@1
      displayName: 'download settings.xml for Maven'
      name: settingsxml
      inputs:
        secureFile: 'settings.xml'
        retryCount: '2'
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'deploy'
        options: '-s $(settingsxml.secureFilePath)'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: true
        sonarQubeRunAnalysis: false